# Project
version=16.0.1
group=dev.thomasglasser.tommylib

# Mod options
mod_name=TommyLib
mod_author=Thomas Glasser
mod_id=tommylib
contributors=
description=A multiloader library holding common code I need in my mods.
license=GPL-3.0
license_url=https://www.gnu.org/licenses/gpl-3.0.html
github_name=TommyLib
java_version=21

# Common
minecraft_version=1.21
previous_minecraft_version=1.20.6
next_minecraft_version=1.21.1
mdg_version=0.1.93
mixin_version=0.13.0+mixin.0.8.5
mixinextras_version=0.3.5

# Parchment
parchment_minecraft_version=1.20.6
parchment_version=2024.06.16

# Dependencies
playeranimator_version=1.0.2-rc1+1.20.4
sbl_version=1.14.3
tslateffectslib_version=1.9
geckolib_version=4.5.5

# NeoForge
neoforge_version=21.0.16-beta
major_fml_version=4

# Fabric
fabric_version=0.100.3+1.21
fabric_loader_version=0.15.11
loom_version=1.7.+

# Gradle
org.gradle.jvmargs=-Xms2048m -Xmx4096m -XX:ReservedCodeCacheSize=1024m -Dorg.gradle.internal.http.socketTimeout=3000 -Dorg.gradle.internal.http.connectionTimeout=3000
org.gradle.daemon=false