# Project
version=31.0.0
group=dev.thomasglasser.tommylib

# Mod options
mod_name=TommyLib
mod_author=Thomas Glasser
mod_id=tommylib
description=A multiloader library holding common code I need in my mods.
license=GPL-3.0
license_url=https://www.gnu.org/licenses/gpl-3.0.html
github_name=TommyLib
java_version=21

# Common
minecraft_version=1.21.5
previous_minecraft_version=1.21.4
next_minecraft_version=1.21.6
mdg_version=2.0.80
neoform_version=20250325.162830
mixin_version=0.15.2+mixin.0.8.7
mixinextras_version=0.4.1

# Parchment
parchment_minecraft_version=1.21.4
parchment_version=2025.03.23

# Dependencies
playeranimator_version=2.0.2+1.21.5
smartbrainlib_version=1.16.7
geckolib_version=5.0-alpha2
sherdsapi_version=6.1.0

# NeoForge
neoforge_version=21.5.39-beta
major_fml_version=7

# Fabric
fabric_version=0.120.0+1.21.5
fabric_loader_version=0.16.13
loom_version=1.10.+

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
