# Project
version=32.0.1
group=dev.thomasglasser.tommylib

# Mod options
mod_name=TommyLib
mod_author=Thomas Glasser
mod_id=tommylib
description=A multiloader library holding common code I need in my mods.
license=LGPL-3.0
license_url=https://www.gnu.org/licenses/lgpl-3.0-standalone.html
github_name=TommyLib
java_version=21

# Common
minecraft_version=1.21.11
next_minecraft_version=26.1.0
mdg_version=2.0.123
neoform_version=20251209.172050
mixin_version=0.16.5+mixin.0.8.7
mixinextras_version=0.5.0

# Parchment
parchment_minecraft_version=1.21.10
parchment_version=2025.10.12

# Dependencies
smartbrainlib_version=1.16.11
geckolib_version=5.4-alpha-1
sherdsapi_version=6.1.5-a

# NeoForge
neoforge_version=21.11.3-beta
major_fml_version=10

# Fabric
fabric_version=0.139.4+1.21.11
fabric_loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
