modLoader="javafml"
license="${license}"
issueTrackerURL="https://github.com/thomasglasser/${github_name}/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/thomasglasser/${github_name}"
authors="${mod_author}"
description='''
${description}
'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},${next_minecraft_version})"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"