plugins {
	id "tommylib-loader"
	id 'net.neoforged.moddev' version "${mdg_version}"
}

neoForge {
	version = "${neoforge_version}"

	def at = rootProject.project(":common").file('src/main/resources/META-INF/accesstransformer.cfg')
	if (file(at).exists()) {
		accessTransformers = [at]
	}

	runs {
		configureEach {
			systemProperties.put('terminal.ansi', 'true')
		}
		client {
			client()
			ideName = "NeoForge Client"
			gameDirectory = project.layout.projectDirectory.dir('runs/client')
		}
		server {
			server()
			ideName = "NeoForge Server"
			gameDirectory = project.layout.projectDirectory.dir('runs/server')
		}
		data {
			clientData()
			ideName = "NeoForge Data Generation"
			gameDirectory = project.layout.projectDirectory.dir('runs/data')
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', rootProject.project(":common").file('src/generated/resources/').getAbsolutePath(), '--existing', rootProject.project(":common").file('src/main/resources/').getAbsolutePath()
		}
	}

	mods {
		tommylib {
			sourceSet sourceSets.main
		}
	}
}

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

dependencies {
	// Common
//	compileOnly "net.tslat.smartbrainlib:SmartBrainLib-neoforge-${minecraft_version}:${smartbrainlib_version}"
	compileOnly "com.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
//	compileOnly("dev.thomasglasser.sherdsapi:sherdsapi-neoforge-${minecraft_version}:${sherdsapi_version}") {
//        transitive = false
//    }
}
