plugins {
	id "tommylib-loader"
	id 'net.neoforged.moddev' version "${mdg_version}"
}

neoForge {
	version = "${neoforge_version}"

	parchment {
		minecraftVersion = parchment_minecraft_version
		mappingsVersion = parchment_version
	}

	def at = '../common/src/main/resources/META-INF/accesstransformer.cfg'
	if (file(at).exists()) {
		accessTransformers = [at]
	}

	runs {
		client {
			client()
			ideName = "NeoForge Client"
			gameDirectory = project.layout.projectDirectory.dir('runs/client')
		}
		server {
			server()
			ideName = "NeoForge Server"
			gameDirectory = project.layout.projectDirectory.dir('runs/server')
		}
		data {
			data()
			ideName = "NeoForge Data Generation"
			gameDirectory = project.layout.projectDirectory.dir('runs/data')
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', rootProject.project(":common").file('src/generated/resources/').getAbsolutePath(), '--existing', rootProject.project(":common").file('src/main/resources/').getAbsolutePath()
		}
	}

	mods {
		tommylib {
			sourceSet sourceSets.main
		}
	}
}

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

dependencies {
	// Common
	compileOnly "dev.kosmx.player-anim:player-animation-lib-forge:${playeranimator_version}"
	compileOnly "net.tslat.effectslib:TslatEffectsLib-neoforge-${previous_minecraft_version}:${tslateffectslib_version}"
//	compileOnly "net.tslat.effectslib:TslatEffectsLib-neoforge-${minecraft_version}:${tslateffectslib_version}"
	compileOnly "net.tslat.smartbrainlib:SmartBrainLib-neoforge-${minecraft_version}:${smartbrainlib_version}"
	compileOnly "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
	compileOnly "dev.thomasglasser.sherdsapi:sherdsapi-neoforge-${minecraft_version}:${sherdsapi_version}"
}